default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_booking_app_backend_development
  port: 5432

test:
  <<: *default
  database: movie_booking_app_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: movie_booking_app_backend_production
